#!/usr/bin/env python3
"""Merge librechat-system.yaml + librechat-user.yaml → librechat.yaml.

System template provides: version, mcpSettings, mcpServers, interface,
fileConfig, endpoints.agents.  These keys always come from the system template.

User overlay provides everything else: cache, registration,
endpoints.custom (LLM providers), and any other LibreChat settings.

Usage:
    python merge-librechat-yaml.py <system.yaml> <user.yaml> <output.yaml> [home_dir]

If home_dir is given, replaces __HOME__ placeholders in the output.
"""

import os
import sys

import yaml

# Keys that are exclusively owned by the system template.
# User overlay values for these keys are ignored.
SYSTEM_KEYS = {"version", "mcpSettings", "mcpServers", "interface", "fileConfig"}


def deep_merge(base, overlay):
    """Recursively merge overlay into base. Overlay wins on conflicts."""
    merged = dict(base)
    for key, val in overlay.items():
        if key in merged and isinstance(merged[key], dict) and isinstance(val, dict):
            merged[key] = deep_merge(merged[key], val)
        else:
            merged[key] = val
    return merged


def replace_home(obj, home_dir):
    """Recursively replace __HOME__ in string values."""
    if isinstance(obj, str):
        return obj.replace("__HOME__", home_dir)
    if isinstance(obj, dict):
        return {k: replace_home(v, home_dir) for k, v in obj.items()}
    if isinstance(obj, list):
        return [replace_home(v, home_dir) for v in obj]
    return obj


def merge(system_path, user_path, home_dir=None):
    """Load and merge system + user YAML, return merged dict."""
    with open(system_path) as f:
        system = yaml.safe_load(f) or {}
    with open(user_path) as f:
        user = yaml.safe_load(f) or {}

    # Start with system as base, overlay user settings
    merged = deep_merge(system, user)

    # Force system-owned keys back (user cannot override these)
    for key in SYSTEM_KEYS:
        if key in system:
            merged[key] = system[key]

    # endpoints is special: system owns 'agents', user owns 'custom'
    sys_endpoints = system.get("endpoints", {})
    user_endpoints = user.get("endpoints", {})
    merged_endpoints = deep_merge(sys_endpoints, user_endpoints)
    # Always keep system's agents config
    if "agents" in sys_endpoints:
        merged_endpoints["agents"] = sys_endpoints["agents"]
    if merged_endpoints:
        merged["endpoints"] = merged_endpoints

    # Replace __HOME__ placeholders
    if home_dir:
        merged = replace_home(merged, home_dir)

    return merged


class _YamlStr(str):
    """String subclass for literal block style in YAML output."""


def _str_representer(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


yaml.add_representer(_YamlStr, _str_representer)


def _convert_multiline(obj):
    """Convert multiline strings to _YamlStr for literal block output."""
    if isinstance(obj, str):
        return _YamlStr(obj) if "\n" in obj else obj
    if isinstance(obj, dict):
        return {k: _convert_multiline(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_convert_multiline(v) for v in obj]
    return obj


def write_yaml(data, output_path):
    """Write merged config to YAML file."""
    data = _convert_multiline(data)
    header = (
        "# LibreChat configuration — auto-generated by merge-librechat-yaml.py\n"
        "# System settings from librechat-system.yaml (do not edit here).\n"
        "# User settings from librechat-user.yaml (edit that file instead).\n"
    )
    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(
            data,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=120,
        )


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <system.yaml> <user.yaml> <output.yaml> [home_dir]")
        sys.exit(1)

    system_path = sys.argv[1]
    user_path = sys.argv[2]
    output_path = sys.argv[3]
    home_dir = sys.argv[4] if len(sys.argv) > 4 else None

    if not os.path.isfile(system_path):
        print(f"Error: system template not found: {system_path}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(user_path):
        print(f"Error: user overlay not found: {user_path}", file=sys.stderr)
        sys.exit(1)

    merged = merge(system_path, user_path, home_dir)
    write_yaml(merged, output_path)
    print(f"Merged config written to {output_path}")


if __name__ == "__main__":
    main()
